### ISSUE TITLE
Pull Request issue

### ISSUE THREAD

**Issue by tdeang** [cesalazar/berlinblockchainweek#87]
Hi, attached you can find the .txt of the README for Non Fungible Future, a new event I'm committing.

[readme.txt](https://github.com/cesalazar/berlinblockchainweek/files/2300660/readme.txt)

I followed the process but I can't do the pull req (last point) as I get asked to compare base/master.

How can I solve it?

**Comment by cesalazar** [comment]
Thanks for trying to submit this event!

I'm not sure why you're not able to do the PR, but it's possible your fork is behind mine (it is outdated). In order to try to solve it create a PR on _your_ repository, then merge my `master` into your `master`.

This is the link: https://github.com/tdeang/berlinblockchainweek/compare/master...cesalazar:master (head fork, on the right, is my repo. The left needs to be yours).

After merging the PR on your repo, you should be able to create a PR on mine.

Let me know if you need further help.

**Comment by cesalazar** [comment]
The format of the `readme.txt` you sent is quite good. I can publish for you, if you don't feel like solving the problem on your repo. Please let me know soon, as I'm going to merge into master and your repo will be behind again.

**Comment by tdeang** [comment]
I was trying to do it now, but it'd be great if you could publish it for me!

Thanks a lot for your help :)

T

**Comment by cesalazar** [comment]
No prob. I'll publish in a bit.
